# == export: standard-setup / begin ==
---
name: Merge Gatekeeper

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  merge-gatekeeper:
    runs-on: ubuntu-latest
    # Restrict permissions of the GITHUB_TOKEN.
    # Docs: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      checks: read
      statuses: read
    steps:
      - name: Run Merge Gatekeeper
        # NOTE: Pinned to commit SHA for supply-chain safety. Update by replacing
        #       both the SHA and the version tag in the trailing comment.
        #       https://github.com/upsidr/merge-gatekeeper/tags
        #       https://github.com/upsidr/merge-gatekeeper/branches
        uses: upsidr/merge-gatekeeper@09af7a82c1666d0e64d2bd8c01797a0bcfd3bb5d # v1.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
# == export: standard-setup / end ==

# == export: custom-job-name / begin ==
---
name: Merge Gatekeeper

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  merge-gatekeeper-custom:
    runs-on: ubuntu-latest
    name: Custom Name for Merge Gatekeeper
    # Restrict permissions of the GITHUB_TOKEN.
    # Docs: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      checks: read
      statuses: read
    steps:
      - name: Run Merge Gatekeeper
        uses: upsidr/merge-gatekeeper@09af7a82c1666d0e64d2bd8c01797a0bcfd3bb5d # v1.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          self: Custom Name for Merge Gatekeeper # This must match with the Job name provided above.
# == export: custom-job-name / end ==
