---
name: Merge Gatekeeper

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  gatekeeper:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      statuses: read
    steps:
      - name: Run gatekeeper
        uses: argandtech/gatekeeper@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
