name: "Merge Gatekeeper"
description: "Get better merge control"
branding:
  icon: git-merge
  color: orange
inputs:
  token:
    description: "set github token"
    required: true
  self:
    description: "set self job name"
    required: false
    default: "merge-gatekeeper"
  interval:
    description: "set validate interval second (default 5)"
    required: false
    default: "5"
  github-client-retry:
    description: "set retry count for GitHub client (default 0)"
    required: false
    default: "0"
  timeout:
    description: "set validate timeout second (default 600)"
    required: false
    default: "600"
  ignored:
    description: "set ignored jobs (comma-separated list)"
    required: false
    default: ""
  ref:
    description: "set ref of github repository. the ref can be a SHA, a branch name, or tag name"
    required: false
    default: ${{ github.event.pull_request.head.sha }}
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "validate"
    - "--token=${{ inputs.token }}"
    - "--self=${{ inputs.self }}"
    - "--interval=${{ inputs.interval }}"
    - "--github-client-retry=${{ inputs.github-client-retry }}"
    - "--ref=${{ inputs.ref }}"
    - "--timeout=${{ inputs.timeout }}"
    - "--ignored=${{ inputs.ignored }}"
