name: Build

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main
      - release/v*
    paths:
      - main.go
      - version.txt
      - internal/**
      - go.mod
      - go.sum

env:
  GO_VERSION: 1.16.7

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Go Build
        run: go build ./...
      - name: Run Go Test
        run: go test ./...
