---
name: gatekeeper

on:
  pull_request:
    branches:
      - main

jobs:
  gatekeeper:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      statuses: read
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gatekeeper
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
